package levonberberyan.chesstoolbylevon.chessmove;

public enum ChessMoveTypeEnum {
	MOVEMENT,
	SIMPLE_ATTACK,
	PROMOTION,
	EN_PASSANT_ATTACK,
	CHECK_EFFECT,
	CASTLING_WHITES_KING_SIDE,
	CASTLING_WHITES_QUEEN_SIDE,
	CASTLING_BLACKS_KING_SIDE,
	CASTLING_BLACKS_QUEEN_SIDE;
}
